apiVersion: v1
kind: Service
metadata:
  name: microservice-lb
  namespace: development
spec:
  type: LoadBalancer
  selector:
    app: microservice
  ports:
    - name: http
      port: 80
      targetPort: 8080