apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-plugins
  namespace: ci
data:
  plugins.txt: |
    kubernetes
    kubernetes-cli
    workflow-aggregator
    git
    git-client
    credentials
    plain-credentials
    config-file-provider
    blueocean
    pipeline-stage-view
    workflow-job
    workflow-cps
    workflow-api
    workflow-support
    workflow-multibranch
    workflow-scm-step
    script-security